@echo off
echo Building Browser History Analyzer...
echo Compiling Java files...
javac -cp ".;sqlite-jdbc.jar" *.java
echo Creating JAR file...
jar cf HistoryAnalyzer.jar *.class
echo ✅ Build complete! Now use Launch4j to create HistoryAnalyzer.exe
pause